spring.application.name=S12student-management-system 
# Database Configuration 
spring.datasource.url=jdbc:mysql://localhost:3306/hibernate_db
spring.datasource.username=root
spring.datasource.password=Sahith@mysql77

# Hibernate Configuration 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
# Server Port (Optional) 
server.port=8085